### List all books
GET http://127.0.0.1:8000/books

### Get a book by ID
GET http://127.0.0.1:8000/books/5

### Create a new book
POST http://127.0.0.1:8000/books
Content-Type: application/json

{
    "title": "test2",
    "author": "George Orwell",
    "isbn": "9780451524935",  
    "category": "Fiction",
    "status": "available"
}

### Update a book
PUT http://127.0.0.1:8000/books/4
Content-Type: application/json

{
    "title": "updating test1",
    "author": "George Orwell",
    "isbn": "9780452284241",  
    "category": "changing Fiction to Science",
    "status": "available"
}

### Delete a book
DELETE http://127.0.0.1:8000/books/5

### Search by title
GET http://127.0.0.1:8000/books/find?title=updating%20test1

### Search by author
GET http://127.0.0.1:8000/books/find?author=George%20Orwell

### Search by category
GET http://127.0.0.1:8000/books/find?category=Fiction

### Multiple parameters
GET http://127.0.0.1:8000/books/find?author=George%20Orwell&category=Fiction